general {
    col.active_border = rgba(E4BBF3ff) rgba(472952ff) 45deg
    col.inactive_border = rgba(201F4Aff) rgba(6E56BAff) 45deg
}

group {
    col.border_active = rgba(E4BBF3ff) rgba(472952ff) 45deg
    col.border_inactive = rgba(201F4Acc) rgba(6E56BAcc) 45deg
    col.border_locked_active = rgba(CFD6D2ff) rgba(060706ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(E0E1DEcc) 45deg
}
